/**
 * Created by edo on 06/05/2017.
 */
import {InjectionToken} from "@angular/core";

export const APP_CONFIG = new InjectionToken("app.config");

const SERVICE_BASE_URL: string = process.env.API_URL;

const LANG_US = {
    'reminderDocReturnList': 'Overdue Document Borrow List',
    'documentRegistration': 'Document Registration',
    'boxRegistration': 'Box Registration',
    'lending': 'Lending',
    'viewLendingHistory': 'Lending History',
    'informationAndDocLending': 'Information / Document Lending',
    'boxSending': 'Box Sending ',
    'boxLending': 'Box Lending ',
    'boxMaintenance': 'Box Maintenance',
    'boxMaintenanceRequest': 'Box Maintenance Request',
    'boxMaintenanceRequestApproval': 'Box Maintenance Request Approval',
    'documentReturning': 'Document Return',
    'documentReturningApproval': 'Document Return Approval',
    'documentLending': 'Document Lending',
    'documentLendingReceive': 'Document Lending Receive',
    'documentLendingApproval': 'Document Lending Approval',
    'boxMaintenanceApproval': 'Box Maintenance Approval',
    'boxLendingApproval': 'Approval Lending Box',
    'boxReceiving': 'Receiving Box',
    'boxReturn': 'Box Return',
    'boxReturnApproval': 'Approval Box Return',
    'documentSearch': 'Document Search',
    'registration': 'Registration',
    'borrowRegistration': 'Borrow Document Registration',
    'checkInApproval': 'Approval Pickup Box',
    'pickupBox': 'Pickup Box Request',
    'depositDocumentRegistrationApproval': 'Approval Document Registration',
    'browse': 'browse',
    'document': 'Document',
    'documentNo': 'Document No',
    'documentName': 'Document Name',
    'depositDocumentRegistration': 'Document Registration',
    'depositBoxRegistration': 'Box Registration',
    'invalidRegistration': 'Invalid Registration',
    'exceededSize': 'Invalid Size',
    'infoRegistration': 'Info Registration',
    'invalidPeriod': 'Invalid Period',
    'advanceStartDate': 'Start date is after end date',
    'overlimitSize': 'File size is overlimit',
    'spvSend': 'Send To Supervisor',
    'noDataFound': 'No Data Found',
    'submitApproval': 'Submit Approval',
    'noRecord': 'No Record Found',
    'view': 'View',
    'add': 'Add',
    'update': 'Update',
    'delete': 'Delete',
    'search': 'Search',
    'save': 'Save',
    'reset': 'Reset',
    'close': 'Close',
    'choose': 'Choose',
    'small': 'Small',
    'maintenance': 'Maitenance',
    'medium': 'Medium',
    'large': 'Large',
    'internal': 'Internal',
    'vendor': 'Vendor',
    'required': 'Required',
    'receive': 'Receive',
    'return': 'Return',
    'returning': 'Returning',
    'idBox': 'Box ID',
    'fileUpload': 'File Attachment',
    'idDoc': 'Document ID',
    'workingUnit': 'Working Unit',
    'boxDescription': 'Box Description',
    'depositLocation': 'Box Location',
    'depositType': 'Deposit Type',
    'depositRoom': 'Box Deposit Room',
    'depositShelf': 'Box Deposit Shelf',
    'startValidDate': 'Start Valid Date',
    'endValidDate': 'End Valid Date',
    'documentType': 'Document Type',
    'sheetNo': 'Total Sheets',
    'description': 'Description',
    'keyword': 'Keyword',
    'attachment': 'Attachment',
    'viewDetailBox': 'View box detail',
    'deleteBox': 'Delete a box',
    'updateBox': 'Update box information',
    'viewDetailDoc': 'View document detail',
    'deleteDoc': 'delete a document',
    'updateDoc': 'update document information',
    'send': 'Send',
    'approval': 'Approval',
    'approve': 'Approve',
    'reject': 'Reject',
    'reason': 'Reason',
    'request': 'Request',
    'overdue': 'Overdue',
    'more3': 'More Than 3 Days',
    'between13': '1-3 Days',
    'dueDate': 'Due Date',
    'today': 'Today',
    'login': 'Login',
    'userName': 'User Name',
    'password': 'Password',
    'invalidLogin': 'Invalid User & Password'
};

const LANG_ID = {
    'reminderDocReturnList': 'Daftar Pengembalian Arsip Habis Batas Waktu',
    'documentRegistration': 'Pendaftaran Arsip',
    'boxRegistration': 'Pendaftaran Box',
    'lending': 'Peminjaman',
    'viewLendingHistory': 'Histori Peminjaman',
    'informationAndDocLending': 'Informasi / Peminjaman Arsip',
    'boxSending': 'Pengiriman Box',
    'boxLending': 'Peminjaman Box',
    'boxMaintenance': 'Pengkinian Data Box',
    'boxMaintenanceRequest': 'Pengajuan Pengkinian Data Box',
    'boxMaintenanceRequestApproval': 'Persetujuan Pengajuan Pengkinian Data Box',
    'documentReturning': 'Pengembalian Arsip',
    'documentReturningApproval': 'Persetujuan Pengembalian Arsip',
    'documentLending': 'Peminjaman Arsip',
    'documentLendingApproval': 'Persetujuan Peminjaman Arsip',
    'documentLendingReceive': 'Penerimaan Peminjaman Arsip',
    'boxMaintenanceApproval': 'Persetujuan Pengkinian Data Box',
    'boxLendingApproval': 'Persetujuan Peminjaman Box',
    'boxReceiving': 'Penerimaan Box',
    'boxReturn': 'Pengembalian Box',
    'boxReturnApproval': 'Persetujuan Pengembalian Box',
    'documentSearch': 'Pencarian Arsip',
    'registration': 'Pendaftaran',
    'borrowRegistration': 'Peminjaman Arsip',
    'checkInApproval': 'Persetujuan Pickup Box',
    'pickupBox': 'Pengajuan Pickup Box',
    'depositDocumentRegistrationApproval': 'Persetujuan Registrasi Arsip',
    'browse': 'Jelajah File',
    'document': 'Arsip',
    'documentNo': 'Nomor Arsip',
    'documentName': 'Nama Arsip',
    'depositDocumentRegistration': 'Registrasi Arsip',
    'depositBoxRegistration': 'Registrasi Box',
    'invalidRegistration': 'Kesalahan Registrasi',
    'exceededSize': 'Kesalahan Ukuran',
    'infoRegistration': 'Informasi Registrasi',
    'invalidPeriod': 'Kesalahan periode',
    'advanceStartDate': 'Tanggal mulai setelah tanggal akhir',
    'overlimitSize': 'Ukuran file terlalu besar',
    'spvSend': 'Kirim Ke Supervisor',
    'noDataFound': 'Data tidak ditemukan',
    'submitApproval': 'Kirim Untuk Persetujuan',
    'noRecord': 'Tidak ada data yang ditemukan',
    'view': 'Lihat',
    'add': 'Tambah',
    'update': 'Ubah',
    'delete': 'Hapus',
    'search': 'Cari',
    'save': 'Simpan',
    'reset': 'Batal',
    'close': 'Tutup',
    'choose': 'Pilih',
    'small': 'Kecil',
    'maintenance': 'Pengkinian',
    'medium': 'Sedang',
    'large': 'Besar',
    'internal': 'Internal',
    'vendor': 'Vendor',
    'required': 'Dibutuhkan',
    'receive': 'Diterima',
    'return': 'Dikembalikan',
    'returning': 'Pengembalian',
    'idBox': 'ID Box',
    'idDoc': 'ID Arsip',
    'fileUpload': 'File Lampiran',
    'workingUnit': 'Unit kerja',
    'boxDescription': 'Deskripsi box',
    'depositLocation': 'Lokasi box',
    'depositType': 'Tipe Penyimpanan',
    'depositRoom': 'Ruang penyimpanan box',
    'depositShelf': 'Rak penyimpanan box',
    'startValidDate': 'Tanggal mulai periode berlaku',
    'endValidDate': 'Tanggal akhir periode berlaku',
    'documentType': 'Tipe Arsip',
    'sheetNo': 'Jumlah Lembar',
    'description': 'Deskripsi',
    'keyword': 'Kata Kunci',
    'attachment': 'Lampiran',
    'viewDetailBox': 'Lihat informasi box',
    'deleteBox': 'Hapus box',
    'updateBox': 'Pembaruan informasi box',
    'viewDetailDoc': 'Lihat informasi arsip',
    'deleteDoc': 'Hapus dokumen',
    'updateDoc': 'Pembaruan informasi arsip',
    'send': 'Kirim',
    'approval': 'Persetujuan',
    'approve': 'Disetujui',
    'reject': 'Ditolak',
    'reason': 'Alasan',
    'request': 'Pengajuan',
    'overdue': 'Keterlambatan',
    'more3': 'Lebih dari 3 Hari',
    'between13': '1-3 Hari',
    'dueDate': 'Jatuh Tempo',
    'today': 'Hari Ini',
    'login': 'Masuk',
    'userName': 'ID Pengguna',
    'password': 'Kata Kunci',
    'invalidLogin': 'Kesalahan ID Pengguna'
};

const ERROR_DICT = {
    'error400': 'Bad Request',
    'error401': 'Unauthorized',
    'error403': 'Forbidden',
    'error404': 'Page Not Found',
    'error504': 'Getway Timeout',
    'error500': 'Server Error'
}

const MENU_CODE = {}

const SERVICE_LIST = {
    'addBoxRegistration': 'ADD_BOX_REGISTRATION',
    'getListBoxRegistrationPaging': 'GET_LIST_BOX_REGISTRATION_PAGING',
}

export const appConfig = {
    'appName': 'Square Dare',
    'appVersion': '1.0.0',
    'year': '2017',
    'company': 'Square Techno Indonesia',
    'serviceBaseUrl': SERVICE_BASE_URL,
    'serviceList': SERVICE_LIST,
    'lsAuthKey': 'av',
    'tokenUserName': 'un',
    'tokenMenuUser': 'mn',
    'tokenUserRole': 'rl',
    'tokenKey': 'sk',
    'tokenService': 'service',
    'tokenBranchCode': 'bc',
    'tokenAppName': 'ap',
    'tokenAppVersion': 'vr',
    'prefLang': 'pl',
    'addAction': 'add',
    'updateAction': 'update',
    'menuCode': MENU_CODE,
    'dictionary': {
        'ID': LANG_ID,
        'EN': LANG_US
    },
    'errorDict': ERROR_DICT,
};
